USE ASSIGNMENT2

--1
SELECT Quiz_ID, Description FROM LECTURE, QUIZ WHERE Lecture_Name = 'Why we program' AND LECTURE.Course_ID = QUIZ.Course_ID AND LECTURE.Lecture_number = QUIZ.Lecture_number ORDER BY Quiz_ID

--2
SELECT USERTB.User_ID, USERTB.First_Name, USERTB.Last_Name, TEACHER.Degree, UNIVERSITY.University_name  FROM USERTB, TEACHER, CREAT_COURSE, UNIVERSITY WHERE USERTB.User_ID = TEACHER.User_ID AND CREAT_COURSE.Teacher_ID = TEACHER.User_ID AND UNIVERSITY.University_ID = TEACHER.University_ID AND CREAT_COURSE.Course_ID = '5000002' ORDER BY USERTB.Last_Name

--3
SELECT COURSE.Course_ID , COURSE.Course_name, COURSE.SPECIALIZATION, COURSE.Level, COURSE.Fee, COUNT(*) AS Learners FROM COURSE, ENROLL_COURSE WHERE COURSE.Course_ID = ENROLL_COURSE.Course_ID GROUP BY COURSE.Course_ID , COURSE.Course_name, COURSE.SPECIALIZATION, COURSE.Level, COURSE.Fee HAVING COUNT(*) > 3 ORDER BY COURSE.Course_ID

--4
SELECT USERTB.User_ID, USERTB.Username, USERTB.First_Name, USERTB.Last_Name, COUNT(*) AS TotalCourseCreated FROM USERTB, TEACHER, CREAT_COURSE WHERE USERTB.User_ID = TEACHER.User_ID AND TEACHER.User_ID = CREAT_COURSE.Teacher_ID GROUP BY USERTB.User_ID, USERTB.Username, USERTB.First_Name, USERTB.Last_Name HAVING COUNT(*) > 0 ORDER BY USERTB.User_ID